version: '3.8'

services:
  redis-full-text-search:
    image: redis:8.0-M04  # Use Redis 8.0
    container_name: redis_8_demo_full_text_search
    restart: always
    ports:
      - "6379:6379"

  redis-probabilistic:
    image: redis:8.0-M04  # Use Redis 8.0
    container_name: redis_8_demo_probabilistic
    restart: always
    ports:
      - "6380:6379"
        
  redis-vss:
    image: redis:8.0-M04  # Use Redis 8.0
    container_name: redis_8_demo_vss
    restart: always
    ports:
      - "6381:6379"